---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-service-account
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-sa-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: demo-service-account
type: kubernetes.io/service-account-token